---
# handlers file for systemupdates
- name: Reboot the server if required
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: ansible_facts['kernel_version'] != ansible_facts['running_kernel_version']
  tags: reboot