---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check for recent dist-upgrade in apt history log
      ansible.builtin.shell: |
        grep -q "Commandline: apt-get dist-upgrade" /var/log/apt/history.log
      register: dist_upgrade_check
      ignore_errors: yes  # Continue even if the command fails (e.g., no log entry found)

    - name: Fail if dist-upgrade has not been run recently
      ansible.builtin.fail:
        msg: "The system has not run 'apt dist-upgrade' recently."
      when: dist_upgrade_check.rc != 0  # Fail if the grep command did not find a match

    - name: Success message if dist-upgrade has been run recently
      ansible.builtin.debug:
        msg: "The system has run 'apt dist-upgrade' recently."
      when: dist_upgrade_check.rc == 0  # Success if the grep command found a match